### ISSUE TITLE
Can you add a way for me to tip you for this

### ISSUE THREAD

**Issue by drifterz28** [LuukEsselbrugge/Volve#1]
This is so cool and something I have wanted to do for a long time now. I think you should add a way for us to tip you for your work. 

Thanks!

**Comment by LuukEsselbrugge** [comment]
Thank you for the kind words but there is no need for tipping. I'm happy to provide my project and hopefully help others with theirs. I also can't in good conscience receive tips with the state the code is currently in haha.
